### ISSUE TITLE
Error when building the doc with python 3.x

### ISSUE THREAD

**Issue by picca** [PierreRaybaut/guiqwt#39]
/home/picca/Debian/guiqwt/guiqwt/doc/reference/annotations.rst:1: WARNING: autodoc: failed to import module 'guiqwt.annotations'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/annotations.py", line 82, in <module>
    from guiqwt.label import DataInfoLabel
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/label.py", line 58, in <module>
    from guiqwt.curve import CurveItem
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/curve.py", line 210, in <module>
    SELECTED_SYMBOL_PARAM.read_config(CONF, "plot", "selected_curve_symbol")
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 775, in read_config
    self.deserialize(reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 763, in deserialize
    item.deserialize(self, reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 343, in deserialize
    value = self.get_value_from_reader(reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 334, in get_value_from_reader
    return reader.read_any()
  File "/usr/lib/python3/dist-packages/guidata/userconfigio.py", line 125, in read_any
    val = self.conf.get(self.section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 311, in get
    value = self.__get(section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 318, in __get
    value = cp.ConfigParser.get(self, section, option, raw=self.raw)
  File "/usr/lib/python3.4/configparser.py", line 772, in get
    d)
  File "/usr/lib/python3.4/configparser.py", line 371, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.4/configparser.py", line 384, in _interpolate_some
    rawval = parser.get(section, option, raw=True, fallback=rest)
TypeError: get() got an unexpected keyword argument 'raw'
/home/picca/Debian/guiqwt/guiqwt/doc/reference/builder.rst:1: WARNING: autodoc: failed to import module 'guiqwt.builder'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/builder.py", line 66, in <module>
    from guiqwt.curve import CurveItem, ErrorBarCurveItem, GridItem
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/curve.py", line 210, in <module>
    SELECTED_SYMBOL_PARAM.read_config(CONF, "plot", "selected_curve_symbol")
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 775, in read_config
    self.deserialize(reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 763, in deserialize
    item.deserialize(self, reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 343, in deserialize
    value = self.get_value_from_reader(reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 334, in get_value_from_reader
    return reader.read_any()
  File "/usr/lib/python3/dist-packages/guidata/userconfigio.py", line 125, in read_any
    val = self.conf.get(self.section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 311, in get
    value = self.__get(section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 318, in __get
    value = cp.ConfigParser.get(self, section, option, raw=self.raw)
  File "/usr/lib/python3.4/configparser.py", line 772, in get
    d)
  File "/usr/lib/python3.4/configparser.py", line 371, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.4/configparser.py", line 384, in _interpolate_some
    rawval = parser.get(section, option, raw=True, fallback=rest)
TypeError: get() got an unexpected keyword argument 'raw'
/home/picca/Debian/guiqwt/guiqwt/doc/reference/cross_section.rst:1: WARNING: autodoc: failed to import module 'guiqwt.cross_section'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/cross_section.py", line 58, in <module>
    from guiqwt.curve import CurvePlot, ErrorBarCurveItem
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/curve.py", line 210, in <module>
    SELECTED_SYMBOL_PARAM.read_config(CONF, "plot", "selected_curve_symbol")
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 775, in read_config
    self.deserialize(reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 763, in deserialize
    item.deserialize(self, reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 343, in deserialize
    value = self.get_value_from_reader(reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 334, in get_value_from_reader
    return reader.read_any()
  File "/usr/lib/python3/dist-packages/guidata/userconfigio.py", line 125, in read_any
    val = self.conf.get(self.section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 311, in get
    value = self.__get(section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 318, in __get
    value = cp.ConfigParser.get(self, section, option, raw=self.raw)
  File "/usr/lib/python3.4/configparser.py", line 772, in get
    d)
  File "/usr/lib/python3.4/configparser.py", line 371, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.4/configparser.py", line 384, in _interpolate_some
    rawval = parser.get(section, option, raw=True, fallback=rest)
TypeError: get() got an unexpected keyword argument 'raw'
/home/picca/Debian/guiqwt/guiqwt/doc/reference/curve.rst:1: WARNING: autodoc: failed to import module 'guiqwt.curve'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/curve.py", line 210, in <module>
    SELECTED_SYMBOL_PARAM.read_config(CONF, "plot", "selected_curve_symbol")
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 775, in read_config
    self.deserialize(reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 763, in deserialize
    item.deserialize(self, reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 343, in deserialize
    value = self.get_value_from_reader(reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 334, in get_value_from_reader
    return reader.read_any()
  File "/usr/lib/python3/dist-packages/guidata/userconfigio.py", line 125, in read_any
    val = self.conf.get(self.section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 311, in get
    value = self.__get(section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 318, in __get
    value = cp.ConfigParser.get(self, section, option, raw=self.raw)
  File "/usr/lib/python3.4/configparser.py", line 772, in get
    d)
  File "/usr/lib/python3.4/configparser.py", line 371, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.4/configparser.py", line 384, in _interpolate_some
    rawval = parser.get(section, option, raw=True, fallback=rest)
TypeError: get() got an unexpected keyword argument 'raw'
/home/picca/Debian/guiqwt/guiqwt/doc/reference/histogram.rst:1: WARNING: autodoc: failed to import module 'guiqwt.histogram'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/histogram.py", line 64, in <module>
    from guiqwt.curve import CurveItem, CurvePlot
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/curve.py", line 210, in <module>
    SELECTED_SYMBOL_PARAM.read_config(CONF, "plot", "selected_curve_symbol")
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 775, in read_config
    self.deserialize(reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 763, in deserialize
    item.deserialize(self, reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 343, in deserialize
    value = self.get_value_from_reader(reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 334, in get_value_from_reader
    return reader.read_any()
  File "/usr/lib/python3/dist-packages/guidata/userconfigio.py", line 125, in read_any
    val = self.conf.get(self.section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 311, in get
    value = self.__get(section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 318, in __get
    value = cp.ConfigParser.get(self, section, option, raw=self.raw)
  File "/usr/lib/python3.4/configparser.py", line 772, in get
    d)
  File "/usr/lib/python3.4/configparser.py", line 371, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.4/configparser.py", line 384, in _interpolate_some
    rawval = parser.get(section, option, raw=True, fallback=rest)
TypeError: get() got an unexpected keyword argument 'raw'
/home/picca/Debian/guiqwt/guiqwt/doc/reference/image.rst:1: WARNING: autodoc: failed to import module 'guiqwt.image'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/image.py", line 165, in <module>
    from guiqwt.curve import CurvePlot, CurveItem, PolygonMapItem
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/curve.py", line 210, in <module>
    SELECTED_SYMBOL_PARAM.read_config(CONF, "plot", "selected_curve_symbol")
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 775, in read_config
    self.deserialize(reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 763, in deserialize
    item.deserialize(self, reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 343, in deserialize
    value = self.get_value_from_reader(reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 334, in get_value_from_reader
    return reader.read_any()
  File "/usr/lib/python3/dist-packages/guidata/userconfigio.py", line 125, in read_any
    val = self.conf.get(self.section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 311, in get
    value = self.__get(section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 318, in __get
    value = cp.ConfigParser.get(self, section, option, raw=self.raw)
  File "/usr/lib/python3.4/configparser.py", line 772, in get
    d)
  File "/usr/lib/python3.4/configparser.py", line 371, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.4/configparser.py", line 384, in _interpolate_some
    rawval = parser.get(section, option, raw=True, fallback=rest)
TypeError: get() got an unexpected keyword argument 'raw'
/home/picca/Debian/guiqwt/guiqwt/doc/reference/label.rst:1: WARNING: autodoc: failed to import module 'guiqwt.label'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/label.py", line 58, in <module>
    from guiqwt.curve import CurveItem
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/curve.py", line 210, in <module>
    SELECTED_SYMBOL_PARAM.read_config(CONF, "plot", "selected_curve_symbol")
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 775, in read_config
    self.deserialize(reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 763, in deserialize
    item.deserialize(self, reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 343, in deserialize
    value = self.get_value_from_reader(reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 334, in get_value_from_reader
    return reader.read_any()
  File "/usr/lib/python3/dist-packages/guidata/userconfigio.py", line 125, in read_any
    val = self.conf.get(self.section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 311, in get
    value = self.__get(section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 318, in __get
    value = cp.ConfigParser.get(self, section, option, raw=self.raw)
  File "/usr/lib/python3.4/configparser.py", line 772, in get
    d)
  File "/usr/lib/python3.4/configparser.py", line 371, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.4/configparser.py", line 384, in _interpolate_some
    rawval = parser.get(section, option, raw=True, fallback=rest)
TypeError: get() got an unexpected keyword argument 'raw'
/home/picca/Debian/guiqwt/guiqwt/doc/reference/plot.rst:1: WARNING: autodoc: failed to import module 'guiqwt.plot'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/plot.py", line 119, in <module>
    from guiqwt.curve import CurvePlot, PlotItemList
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/curve.py", line 210, in <module>
    SELECTED_SYMBOL_PARAM.read_config(CONF, "plot", "selected_curve_symbol")
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 775, in read_config
    self.deserialize(reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 763, in deserialize
    item.deserialize(self, reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 343, in deserialize
    value = self.get_value_from_reader(reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 334, in get_value_from_reader
    return reader.read_any()
  File "/usr/lib/python3/dist-packages/guidata/userconfigio.py", line 125, in read_any
    val = self.conf.get(self.section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 311, in get
    value = self.__get(section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 318, in __get
    value = cp.ConfigParser.get(self, section, option, raw=self.raw)
  File "/usr/lib/python3.4/configparser.py", line 772, in get
    d)
  File "/usr/lib/python3.4/configparser.py", line 371, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.4/configparser.py", line 384, in _interpolate_some
    rawval = parser.get(section, option, raw=True, fallback=rest)
TypeError: get() got an unexpected keyword argument 'raw'
/home/picca/Debian/guiqwt/guiqwt/doc/reference/pyplot.rst:1: WARNING: autodoc: failed to import module 'guiqwt.pyplot'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/pyplot.py", line 118, in <module>
    from guiqwt.plot import PlotManager
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/plot.py", line 119, in <module>
    from guiqwt.curve import CurvePlot, PlotItemList
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/curve.py", line 210, in <module>
    SELECTED_SYMBOL_PARAM.read_config(CONF, "plot", "selected_curve_symbol")
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 775, in read_config
    self.deserialize(reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 763, in deserialize
    item.deserialize(self, reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 343, in deserialize
    value = self.get_value_from_reader(reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 334, in get_value_from_reader
    return reader.read_any()
  File "/usr/lib/python3/dist-packages/guidata/userconfigio.py", line 125, in read_any
    val = self.conf.get(self.section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 311, in get
    value = self.__get(section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 318, in __get
    value = cp.ConfigParser.get(self, section, option, raw=self.raw)
  File "/usr/lib/python3.4/configparser.py", line 772, in get
    d)
  File "/usr/lib/python3.4/configparser.py", line 371, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.4/configparser.py", line 384, in _interpolate_some
    rawval = parser.get(section, option, raw=True, fallback=rest)
TypeError: get() got an unexpected keyword argument 'raw'
/home/picca/Debian/guiqwt/guiqwt/doc/reference/tools.rst:1: WARNING: autodoc: failed to import module 'guiqwt.tools'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/tools.py", line 277, in <module>
    from guiqwt.annotations import (AnnotatedRectangle, AnnotatedCircle,
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/annotations.py", line 82, in <module>
    from guiqwt.label import DataInfoLabel
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/label.py", line 58, in <module>
    from guiqwt.curve import CurveItem
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/curve.py", line 210, in <module>
    SELECTED_SYMBOL_PARAM.read_config(CONF, "plot", "selected_curve_symbol")
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 775, in read_config
    self.deserialize(reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 763, in deserialize
    item.deserialize(self, reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 343, in deserialize
    value = self.get_value_from_reader(reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 334, in get_value_from_reader
    return reader.read_any()
  File "/usr/lib/python3/dist-packages/guidata/userconfigio.py", line 125, in read_any
    val = self.conf.get(self.section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 311, in get
    value = self.__get(section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 318, in __get
    value = cp.ConfigParser.get(self, section, option, raw=self.raw)
  File "/usr/lib/python3.4/configparser.py", line 772, in get
    d)
  File "/usr/lib/python3.4/configparser.py", line 371, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.4/configparser.py", line 384, in _interpolate_some
    rawval = parser.get(section, option, raw=True, fallback=rest)
TypeError: get() got an unexpected keyword argument 'raw'
/home/picca/Debian/guiqwt/guiqwt/doc/reference/widgets_fit.rst:1: WARNING: autodoc: failed to import module 'guiqwt.widgets.fit'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/widgets/fit.py", line 65, in <module>
    from guiqwt.builder import make
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/builder.py", line 66, in <module>
    from guiqwt.curve import CurveItem, ErrorBarCurveItem, GridItem
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/curve.py", line 210, in <module>
    SELECTED_SYMBOL_PARAM.read_config(CONF, "plot", "selected_curve_symbol")
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 775, in read_config
    self.deserialize(reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 763, in deserialize
    item.deserialize(self, reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 343, in deserialize
    value = self.get_value_from_reader(reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 334, in get_value_from_reader
    return reader.read_any()
  File "/usr/lib/python3/dist-packages/guidata/userconfigio.py", line 125, in read_any
    val = self.conf.get(self.section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 311, in get
    value = self.__get(section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 318, in __get
    value = cp.ConfigParser.get(self, section, option, raw=self.raw)
  File "/usr/lib/python3.4/configparser.py", line 772, in get
    d)
  File "/usr/lib/python3.4/configparser.py", line 371, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.4/configparser.py", line 384, in _interpolate_some
    rawval = parser.get(section, option, raw=True, fallback=rest)
TypeError: get() got an unexpected keyword argument 'raw'
/home/picca/Debian/guiqwt/guiqwt/doc/reference/widgets_rotatecrop.rst:1: WARNING: autodoc: failed to import module 'guiqwt.widgets.rotatecrop'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/widgets/rotatecrop.py", line 33, in <module>
    from guiqwt.builder import make
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/builder.py", line 66, in <module>
    from guiqwt.curve import CurveItem, ErrorBarCurveItem, GridItem
  File "/home/picca/Debian/guiqwt/guiqwt/.pybuild/pythonX.Y_3.4/build/guiqwt/curve.py", line 210, in <module>
    SELECTED_SYMBOL_PARAM.read_config(CONF, "plot", "selected_curve_symbol")
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 775, in read_config
    self.deserialize(reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 763, in deserialize
    item.deserialize(self, reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 343, in deserialize
    value = self.get_value_from_reader(reader)
  File "/usr/lib/python3/dist-packages/guidata/dataset/datatypes.py", line 334, in get_value_from_reader
    return reader.read_any()
  File "/usr/lib/python3/dist-packages/guidata/userconfigio.py", line 125, in read_any
    val = self.conf.get(self.section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 311, in get
    value = self.__get(section, option)
  File "/usr/lib/python3/dist-packages/guidata/userconfig.py", line 318, in __get
    value = cp.ConfigParser.get(self, section, option, raw=self.raw)
  File "/usr/lib/python3.4/configparser.py", line 772, in get
    d)
  File "/usr/lib/python3.4/configparser.py", line 371, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.4/configparser.py", line 384, in _interpolate_some
    rawval = parser.get(section, option, raw=True, fallback=rest)
TypeError: get() got an unexpected keyword argument 'raw'

**Comment by PierreRaybaut** [comment]
Well, as you can see below, everything works for me on Python 3.4.

```shell
C:\Python\guiqwt-qwt>sphinx-build -b html doc doctmp
Running Sphinx v1.3.1
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 27 source files that are out of date
updating environment: 27 added, 0 changed, 0 removed
reading sources... [100%] sift
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] sift
generating indices... genindex py-modindex
highlighting module code... [100%] guiqwt.pyplot
writing additional pages... search
copying images... [100%] images/screenshots/sift3.png
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.

C:\Python\guiqwt-qwt>cd doctmp

C:\Python\guiqwt-qwt\doctmp>7z a -r ..\doc.zip *.*

7-Zip 9.13 beta  Copyright (c) 1999-2010 Igor Pavlov  2010-04-15
Scanning

Creating archive ..\doc.zip

Compressing  .buildinfo
Compressing  .doctrees\development.doctree
Compressing  .doctrees\disthelpers.doctree
Compressing  .doctrees\environment.pickle
Compressing  .doctrees\examples.doctree
Compressing  .doctrees\index.doctree
Compressing  .doctrees\installation.doctree
Compressing  .doctrees\overview.doctree
Compressing  .doctrees\reference\annotations.doctree
Compressing  .doctrees\reference\baseplot.doctree
Compressing  .doctrees\reference\builder.doctree
Compressing  .doctrees\reference\cross_section.doctree
Compressing  .doctrees\reference\curve.doctree
Compressing  .doctrees\reference\histogram.doctree
Compressing  .doctrees\reference\image.doctree
Compressing  .doctrees\reference\index.doctree
Compressing  .doctrees\reference\io.doctree
Compressing  .doctrees\reference\label.doctree
Compressing  .doctrees\reference\panels.doctree
Compressing  .doctrees\reference\plot.doctree
Compressing  .doctrees\reference\pyplot.doctree
Compressing  .doctrees\reference\shapes.doctree
Compressing  .doctrees\reference\signals.doctree
Compressing  .doctrees\reference\styles.doctree
Compressing  .doctrees\reference\tools.doctree
Compressing  .doctrees\reference\widgets_fit.doctree
Compressing  .doctrees\reference\widgets_resizedialog.doctree
Compressing  .doctrees\reference\widgets_rotatecrop.doctree
Compressing  .doctrees\sift.doctree
Compressing  development.html
Compressing  disthelpers.html
Compressing  examples.html
Compressing  genindex.html
Compressing  index.html
Compressing  installation.html
Compressing  objects.inv
Compressing  overview.html
Compressing  py-modindex.html
Compressing  reference\annotations.html
Compressing  reference\baseplot.html
Compressing  reference\builder.html
Compressing  reference\cross_section.html
Compressing  reference\curve.html
Compressing  reference\histogram.html
Compressing  reference\image.html
Compressing  reference\index.html
Compressing  reference\io.html
Compressing  reference\label.html
Compressing  reference\panels.html
Compressing  reference\plot.html
Compressing  reference\pyplot.html
Compressing  reference\shapes.html
Compressing  reference\signals.html
Compressing  reference\styles.html
Compressing  reference\tools.html
Compressing  reference\widgets_fit.html
Compressing  reference\widgets_resizedialog.html
Compressing  reference\widgets_rotatecrop.html
Compressing  search.html
Compressing  searchindex.js
Compressing  sift.html
Compressing  _images\computations.png
Compressing  _images\contrast.png
Compressing  _images\cross_section.png
Compressing  _images\curve_widgets.png
Compressing  _images\fit.png
Compressing  _images\hist2d.png
Compressing  _images\imagefilter.png
Compressing  _images\image_plot_tools.png
Compressing  _images\image_widgets.png
Compressing  _images\mandelbrot.png
Compressing  _images\my_plot_manager.png
Compressing  _images\panorama.png
Compressing  _images\plot.png
Compressing  _images\sift1.png
Compressing  _images\sift2.png
Compressing  _images\sift3.png
Compressing  _images\simple_window.png
Compressing  _images\transform.png
Compressing  _images\__init__.png
Compressing  _modules\guidata\dataset\datatypes.html
Compressing  _modules\guidata\qtwidgets.html
Compressing  _modules\guiqwt\annotations.html
Compressing  _modules\guiqwt\baseplot.html
Compressing  _modules\guiqwt\builder.html
Compressing  _modules\guiqwt\cross_section.html
Compressing  _modules\guiqwt\curve.html
Compressing  _modules\guiqwt\histogram.html
Compressing  _modules\guiqwt\image.html
Compressing  _modules\guiqwt\interfaces.html
Compressing  _modules\guiqwt\io.html
Compressing  _modules\guiqwt\label.html
Compressing  _modules\guiqwt\panels.html
Compressing  _modules\guiqwt\plot.html
Compressing  _modules\guiqwt\pyplot.html
Compressing  _modules\guiqwt\shapes.html
Compressing  _modules\guiqwt\styles.html
Compressing  _modules\guiqwt\tools.html
Compressing  _modules\guiqwt\widgets\base.html
Compressing  _modules\guiqwt\widgets\fit.html
Compressing  _modules\guiqwt\widgets\resizedialog.html
Compressing  _modules\guiqwt\widgets\rotatecrop.html
Compressing  _modules\index.html
Compressing  _modules\qwt\plot.html
Compressing  _modules\qwt\plot_curve.html
Compressing  _modules\qwt\plot_seriesitem.html
Compressing  _modules\qwt\series_store.html
Compressing  _sources\development.txt
Compressing  _sources\disthelpers.txt
Compressing  _sources\examples.txt
Compressing  _sources\index.txt
Compressing  _sources\installation.txt
Compressing  _sources\overview.txt
Compressing  _sources\reference\annotations.txt
Compressing  _sources\reference\baseplot.txt
Compressing  _sources\reference\builder.txt
Compressing  _sources\reference\cross_section.txt
Compressing  _sources\reference\curve.txt
Compressing  _sources\reference\histogram.txt
Compressing  _sources\reference\image.txt
Compressing  _sources\reference\index.txt
Compressing  _sources\reference\io.txt
Compressing  _sources\reference\label.txt
Compressing  _sources\reference\panels.txt
Compressing  _sources\reference\plot.txt
Compressing  _sources\reference\pyplot.txt
Compressing  _sources\reference\shapes.txt
Compressing  _sources\reference\signals.txt
Compressing  _sources\reference\styles.txt
Compressing  _sources\reference\tools.txt
Compressing  _sources\reference\widgets_fit.txt
Compressing  _sources\reference\widgets_resizedialog.txt
Compressing  _sources\reference\widgets_rotatecrop.txt
Compressing  _sources\sift.txt
Compressing  _static\ajax-loader.gif
Compressing  _static\basic.css
Compressing  _static\comment-bright.png
Compressing  _static\comment-close.png
Compressing  _static\comment.png
Compressing  _static\contents.png
Compressing  _static\doctools.js
Compressing  _static\down-pressed.png
Compressing  _static\down.png
Compressing  _static\favicon.ico
Compressing  _static\file.png
Compressing  _static\guiqwt.png
Compressing  _static\jquery-1.11.1.js
Compressing  _static\jquery.js
Compressing  _static\minus.png
Compressing  _static\navigation.png
Compressing  _static\plus.png
Compressing  _static\pygments.css
Compressing  _static\searchtools.js
Compressing  _static\sphinxdoc.css
Compressing  _static\underscore-1.3.1.js
Compressing  _static\underscore.js
Compressing  _static\up-pressed.png
Compressing  _static\up.png
Compressing  _static\websupport.js

Everything is Ok

C:\Python\guiqwt-qwt\doctmp>cd ..

C:\Python\guiqwt-qwt>rmdir /S /Q doctmp

C:\Python\guiqwt-qwt>
```
