### ISSUE TITLE
error launching last test 'transform.py'

### ISSUE THREAD

**Issue by stonebig** [PierreRaybaut/guiqwt#49]
````
(40, 40)
D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\sit
e-packages\guiqwt\image.py:487: RuntimeWarning: overflow encountered in byte_sca
lars
  self.lut = (LUT_MAX/(self.max-self.min),
D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\sit
e-packages\guiqwt\image.py:488: RuntimeWarning: overflow encountered in byte_sca
lars
  -LUT_MAX*self.min/(self.max-self.min),
D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\sit
e-packages\guiqwt\image.py:487: RuntimeWarning: overflow encountered in short_sc
alars
  self.lut = (LUT_MAX/(self.max-self.min),
D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\sit
e-packages\guiqwt\image.py:488: RuntimeWarning: overflow encountered in short_sc
alars
  -LUT_MAX*self.min/(self.max-self.min),
--------------------------------------------------------------------------------

Adding item #0... Done
Adding item #1... Done
Adding item #2... Done
Adding item #3... Done
Adding item #4... Done
Assemble test1: 1500.0 x 1000.0
saving...
Assemble test2: 375.0 x 250.0
````

**Comment by PierreRaybaut** [comment]
Sometimes I see the following traceback (but not yours):
```python
(40, 40)
--------------------------------------------------------------------------------
Adding item #0... Done
Adding item #1... Done
Adding item #2... Done
Adding item #3... Done
Adding item #4... Done
Assemble test1: 1500.0 x 1000.0
saving...
Traceback (most recent call last):
  File "C:\Python\guiqwt-qwt\guiqwt\tests\transform.py", line 168, in <module>
    build_image(items)
  File "C:\Python\guiqwt-qwt\guiqwt\tests\transform.py", line 139, in build_image
    save_image("test1.png", dest)
  File "C:\Python\guiqwt-qwt\guiqwt\tests\transform.py", line 131, in save_image
    io.imwrite(name+".u8.png", data, dtype=np.uint8, max_range=True)
  File "C:\Python\guiqwt-qwt\guiqwt\io.py", line 397, in imwrite
    iohandler.get_writefunc(ext)(fname, arr, **kwargs)
  File "C:\Python\guiqwt-qwt\guiqwt\io.py", line 228, in _imwrite_pil
    img = PIL.Image.fromarray(arr, mode)
  File "C:\WinPython\install\WinPython-64bit-3.4.3.4\python-3.4.3.amd64\lib\site-packages\PIL\Image.py", line 2185, in fromarray
    return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)
  File "C:\WinPython\install\WinPython-64bit-3.4.3.4\python-3.4.3.amd64\lib\site-packages\PIL\Image.py", line 2130, in frombuffer
    core.map_buffer(data, size, decoder_name, None, 0, args)
ValueError: buffer is not large enough
```

**Comment by PierreRaybaut** [comment]
To help me understand, could you add the following line:
```python
            print(self.min, self.max, LUT_MAX/(self.max-self.min), -LUT_MAX*self.min/(self.max-self.min))
```
just before line 487 in guiqwt/image.py which is the beginning of the following block:
```python
            self.lut = (LUT_MAX/(self.max-self.min),
                        -LUT_MAX*self.min/(self.max-self.min),
                        bg, cmap)
```

**Comment by PierreRaybaut** [comment]
...and copy/paste the console output here of course.

**Comment by PierreRaybaut** [comment]
Here is the output for me (without errors):
```python
(40, 40)
0.0 255.0 4.011764705882353 -0.0
0.000431087927432 2.42304800013 422.270642481 -0.182035776083
0.0 255.0 4.011764705882353 -0.0
0 255 4.01176470588 -0.0
0.0 255.0 4.011764705882353 -0.0
0 65535 0.0156099794003 -0.0
0.0 255.0 4.011764705882353 -0.0
-128 127 -1023.0 -130944.0
0.0 255.0 4.011764705882353 -0.0
-32768 32767 -1023.0 -33521664.0
--------------------------------------------------------------------------------
Adding item #0... Done
Adding item #1... Done
Adding item #2... Done
Adding item #3... Done
Adding item #4... Done
--------------------------------------------------------------------------------
Assemble test1: 1500.0 x 1000.0
Saving image: 1000 x 1500 (5859 KB):
 --> uint16
 --> uint8
--------------------------------------------------------------------------------
Assemble test2: 375.0 x 250.0
Saving image: 250 x 375 (366 KB):
 --> uint16
 --> uint8
--------------------------------------------------------------------------------
```

**Comment by stonebig** [comment]
with errors, half is before displaying an odd image, haalf is after
````
(40, 40)
0.0 255.0 4.011764705882353 -0.0
0.000601319953608 2.77931639054 368.155774887 -0.221379413475
0.0 255.0 4.011764705882353 -0.0
0 255 4.01176470588 -0.0
0.0 255.0 4.011764705882353 -0.0
0 65535 0.0156099794003 -0.0
0.0 255.0 4.011764705882353 -0.0
D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\sit
e-packages\guiqwt\image.py:487: RuntimeWarning: overflow encountered in byte_sca
lars
  print(self.min, self.max, LUT_MAX/(self.max-self.min), -LUT_MAX*self.min/(self
.max-self.min))
-128 127 -1023.0 -130944.0
D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\sit
e-packages\guiqwt\image.py:488: RuntimeWarning: overflow encountered in byte_sca
lars
  self.lut = (LUT_MAX/(self.max-self.min),
D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\sit
e-packages\guiqwt\image.py:489: RuntimeWarning: overflow encountered in byte_sca
lars
  -LUT_MAX*self.min/(self.max-self.min),
0.0 255.0 4.011764705882353 -0.0
D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\sit
e-packages\guiqwt\image.py:487: RuntimeWarning: overflow encountered in short_sc
alars
  print(self.min, self.max, LUT_MAX/(self.max-self.min), -LUT_MAX*self.min/(self
.max-self.min))
-32768 32767 -1023.0 -33521664.0
D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\sit
e-packages\guiqwt\image.py:488: RuntimeWarning: overflow encountered in short_sc
alars
  self.lut = (LUT_MAX/(self.max-self.min),
D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\sit
e-packages\guiqwt\image.py:489: RuntimeWarning: overflow encountered in short_sc
alars
  -LUT_MAX*self.min/(self.max-self.min),
--------------------------------------------------------------------------------

Adding item #0... Done
Adding item #1... Done
Adding item #2... Done
Adding item #3... Done
Adding item #4... Done
Assemble test1: 1500.0 x 1000.0
saving...
Traceback (most recent call last):
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64
\lib\site-packages\guiqwt\tests\transform.py", line 168, in <module>
    build_image(items)
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64
\lib\site-packages\guiqwt\tests\transform.py", line 139, in build_image
    save_image("test1.png", dest)
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64
\lib\site-packages\guiqwt\tests\transform.py", line 131, in save_image
    io.imwrite(name+".u8.png", data, dtype=np.uint8, max_range=True)
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64
\lib\site-packages\guiqwt\io.py", line 397, in imwrite
    iohandler.get_writefunc(ext)(fname, arr, **kwargs)
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64
\lib\site-packages\guiqwt\io.py", line 228, in _imwrite_pil
    img = PIL.Image.fromarray(arr, mode)
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64
\lib\site-packages\PIL\Image.py", line 2163, in fromarray
    return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)
  File "D:\WinPythonQt5\basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64
\lib\site-packages\PIL\Image.py", line 2108, in frombuffer
    core.map_buffer(data, size, decoder_name, None, 0, args)
ValueError: buffer is not large enough
````

**Comment by stonebig** [comment]
the image: 
![transform_hurts](https://cloud.githubusercontent.com/assets/4312421/11017661/38f8016a-85a6-11e5-9140-dd1d3d52d388.GIF)

**Comment by PierreRaybaut** [comment]
The commits above should avoid all the overflows with this example.

**Comment by stonebig** [comment]
I'll test tomorrow. eyes are auto-closing

**Comment by stonebig** [comment]
this morning tree seems good now, recompiling with mingwpy (3.4 / 64bit):
````
(40, 40)
--------------------------------------------------------------------------------

Adding item #0... Done
Adding item #1... Done
Adding item #2... Done
Adding item #3... Done
Adding item #4... Done

````
