### ISSUE TITLE
Unable to install on windows

### ISSUE THREAD

**Issue by DawnMe** [PierreRaybaut/guiqwt#75]
When trying to install with `python setup.py build -c mingw32 install`, 
I'm getting the following error:

Warning: `HTML Help Workshop` is required to build CHM documentation file
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "guiqwt.histogram2d" sources
building extension "guiqwt.mandelbrot" sources
building extension "guiqwt._scaler" sources
build_src: building npy-pkg config files
running build_py
running build_ext
Traceback (most recent call last):
  File "setup.py", line 242, in <module>
    'Programming Language :: Python :: 3',
  File "C:\Users\Admin\Anaconda3\lib\site-packages\numpy\distutils\core.py", line 169, in setup
    return old_setup(**new_attr)
  File "C:\Users\Admin\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Admin\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\Admin\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\Admin\Anaconda3\lib\site-packages\numpy\distutils\command\build.py", line 47, in run
    old_build.run(self)
  File "C:\Users\Admin\Anaconda3\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\Admin\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Admin\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\Admin\Anaconda3\lib\site-packages\numpy\distutils\command\build_ext.py", line 117, in run
    force=self.force)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\numpy\distutils\ccompiler.py", line 596, in new_compiler
    compiler = klass(None, dry_run, force)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\numpy\distutils\mingw32ccompiler.py", line 58, in __init__
    dry_run, force)
  File "C:\Users\Admin\Anaconda3\lib\distutils\cygwinccompiler.py", line 126, in __init__
    if self.ld_version >= "2.10.90":
TypeError: unorderable types: NoneType() >= str()

Any way I can fix it?

Thanks,
Shahar

**Comment by DawnMe** [comment]
Never mind, I've installed with pip. Closing the issue.
