### ISSUE TITLE
ValueError: API 'QDate' has already been set to version 1

### ISSUE THREAD

**Issue by picca** [PierreRaybaut/guiqwt#9]
Next error :)

Now thaht I migrate to the API 2 for the signals, I got this error message with spyder 2.3.6

Traceback (most recent call last):
  File "fitnxs.py", line 1362, in <module>
    ui.setupUi(MainWindow)
  File "fitnxs.py", line 998, in setupUi
    self.makewindow()
  File "fitnxs.py", line 1248, in makewindow
    ylabel="ylabel"))
  File "/usr/lib/python2.7/dist-packages/guiqwt/plot.py", line 840, in __init__
    panels=panels)
  File "/usr/lib/python2.7/dist-packages/guiqwt/plot.py", line 772, in __init__
    self.register_tools()
  File "/usr/lib/python2.7/dist-packages/guiqwt/plot.py", line 795, in register_tools
    self.register_all_curve_tools()
  File "/usr/lib/python2.7/dist-packages/guiqwt/plot.py", line 575, in register_all_curve_tools
    self.register_standard_tools()
  File "/usr/lib/python2.7/dist-packages/guiqwt/plot.py", line 498, in register_standard_tools
    import spyderlib.widgets.objecteditor  # analysis:ignore
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/objecteditor.py", line 13, in <module>
    from spyderlib.qt.QtCore import QObject, SIGNAL
  File "/usr/lib/python2.7/dist-packages/spyderlib/qt/__init__.py", line 23, in <module>
    sip.setapi('QDate', 2)
ValueError: API 'QDate' has already been set to version 1

**Comment by picca** [comment]
I discuss with the spyder guyes ;) and it seems that due to the support of jupyter 4.0.0, they migrated spyder from the QT API1 to 2 by default. worst they remove the support for the API 1.
So when guidata or guiawt call spyderlib there is a mismatch between API version.

I blocked the migration of spyder 2.3.6 into debian testing in order to avoid breaking all software depending on spyder BUT the 3.0.0 version of spyder will be API 2 only.

Maybe the soution is to check the version of spyder and set the QT API 1 or 2 depending on that ?
This way it will continu to works. This is a mess because we need to check for this in all packages depending on spyder...

or

modify spyder in order to print a clear message abou tthis API 1 -> API 2 transition.
but this does not solve the usability of guidata, guiqwt with the new spyderib. 

I did not test but using pyQT5 may solve the problem since it use API 2 by default.

what is your opinion about this ?

**Comment by stonebig** [comment]
hi @picca,

What test do you do to get this error ? How do you launch it ?

**Comment by picca** [comment]
I installed the upcoming guidata, guiqwt and python-qwt with the latest 2.3.x spyder series.
then just

guiqwt-tests or guidata-tests

**Comment by mindw** [comment]
Perhaps this - PierreRaybaut/python-qwt#16 can resolve this?

**Comment by picca** [comment]
Yes it does :)

**Comment by picca** [comment]
Just for info because I do not see a commit, in guiqwt. The same solution than the one apply to python-qwt should be apply to guiqwt and guidata :)

**Comment by sailor88128** [comment]
I use pycharm as the IDE, when run with PyQt4 and guiqwt.pyplot imported, the error appears. Any one know how to modify the setting in pycharm?

```
Traceback (most recent call last):
  File "/media/wqk/Documents/Task4-Kuaiyu/Kuaiyu/guiqwt_realtime.py", line 11, in <module>
    from guiqwt.pyplot import * # PlotManager, CurvePlot
  File "/usr/local/lib/python2.7/dist-packages/guiqwt/pyplot.py", line 106, in <module>
    from guidata.qt.QtGui import (QMainWindow, QPrinter, QPainter, QFrame,
  File "/usr/local/lib/python2.7/dist-packages/guidata/__init__.py", line 541, in <module>
    import guidata.config
  File "/usr/local/lib/python2.7/dist-packages/guidata/config.py", line 15, in <module>
    from guidata.configtools import add_image_module_path, get_translation
  File "/usr/local/lib/python2.7/dist-packages/guidata/configtools.py", line 22, in <module>
    from guidata.qt.QtGui import (QFont, QLabel, QPixmap, QIcon, QHBoxLayout,
  File "/usr/local/lib/python2.7/dist-packages/guidata/qt/__init__.py", line 25, in <module>
    sip.setapi('QString', 2)
ValueError: API 'QString' has already been set to version 1
```
