### ISSUE TITLE
Error when trying to execute tests

### ISSUE THREAD

**Issue by eriveraa** [PierreRaybaut/guiqwt#97]
Hi, i´ve just installed guiqwt in my windows 10 machine. However when I try to execute the tests i got this error:

```
>>> from guiqwt import tests
>>> tests.run()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python310\lib\site-packages\guiqwt\tests\__init__.py", line 16, in run
    import guiqwt.config  # Loading icons
  File "C:\Python310\lib\site-packages\guiqwt\config.py", line 18, in <module>
    from guidata import qthelpers
  File "C:\Python310\lib\site-packages\guidata\qthelpers.py", line 20, in <module>
    from qtpy.QtCore import Qt
  File "C:\Python310\lib\site-packages\qtpy\QtCore.py", line 116, in <module>
    Qt.MidButton = Qt.MouseButton.MiddleButton = Qt.MiddleButton
  File "C:\Python310\lib\enum.py", line 480, in __setattr__
    raise AttributeError('Cannot reassign members.')
AttributeError: Cannot reassign members.
```
Any ideas?

**Comment by PierreRaybaut** [comment]
guiqwt works out-of-the-box with Python 3.10 on Windows 10 using [WinPython 3.10.8.0](https://sourceforge.net/projects/winpython/files/WinPython_3.10/3.10.8.0/) for example.

Could you please tell us more on your Python installation? (output of `pip list` for example)
